[package]
name = "xortool"
version = "1.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
hex = "0.4"
walkdir = "2.3"
crossterm = "0.27.0"
atty = "0.2"

